version: "2.3"

services:
  ntfy:
    env_file: .env
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    # user: UID:GID # optional: replace with your own user/group or uid/gid
    volumes:
      - ./:/var/lib/ntfy
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - TZ=UTC    # optional: set desired timezone
      - NTFY_BASE_URL=https://${VIRTUAL_HOST}
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ENABLE_LOGIN=false
      - NTFY_WEB_ROOT=disable
    networks:
      - reverse-proxy
      - default
    healthcheck: # optional: remember to adapt the host:port to your environment
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  reverse-proxy:
    external: true
